owncloud/owncloud-test-middleware

src/gherkin/index.js
src/gherkin/stepDef.test.js

Fixes #18 
support optional text such as `files/folders/resource` in step definitions

Add support for optional text in step definitions

---

src/helpers/sharingHelper.js
src/stepDefinitions/sharingContext.js

This PR adds step to update shared file/folder permission.
For example:
`the user "Alice" has updated permission for shared folder "simple-folder" to "read" permissions`
https://github.com/owncloud/client/issues/7423

[tests-only] added step to update share permission

---

src/app.js
src/gherkin/index.js
src/gherkin/step.test.js
src/gherkin/stepDef.test.js
src/gherkin/testContext.test.js

Add support for cucumber steps with regex
eg
``` js
Given(
/^user "([^"]*)" has been created with default attributes and (without|large|small) skeleton files$/,
async function (userId, skeletonType) {
await deleteUser(userId)
await createDefaultUser(userId, skeletonType)
await initUser(userId)
}
)
```

Add support for step definitions with regex

---

src/gherkin/index.js
src/gherkin/table.test.js

Fix table.rows() method to return correct rows from the table
Fixes https://github.com/owncloud/owncloud-test-middleware/issues/36

Fix table.rows() method to return correct data

---

readme.md
src/app.js

With this PR:
- check if testing app is enable during `init`
- do not let `execute` and `cleanup` before `init`
- part of https://github.com/owncloud/owncloud-test-middleware/issues/25

added testing app check and is initialized check

---

src/stepDefinitions/sharingContext.js

Fix the function to pause between shares in sharingContext
Fixes https://github.com/owncloud/owncloud-test-middleware/issues/51

Fix the function to pause between shares in sharingContext

---

src/stepDefinitions/publicLinkContext.js

This PR refactors step which validates that there is no public link for files/folders.
https://github.com/owncloud/client/pull/9201

refactor step for public link share

---

.drone.star

The triggers for drone were not correct as they used old branch name `master`
This PR changes it to `main`

[CI] change default branch name to main in .drone.star

---

src/stepDefinitions/generalContext.js

Remove the use of `{code}` in the step definitions
we used this for web tests using cucumber but since we really don't need to implement that here we can manually replace the codes ourself.

Remove the use of {code} in step definitions

---

.drone.star

We `installCore` from a specific core commit. That requires the `owncloudci/core` docker image to clone the `owncloud/core` repo, checkout the commit, and build the software (PHP composer, JS yarn etc).
`owncloudci/core:latest` was just rebuilt today. It is based on `owncloudci/php:7.3` and that no longer has JS tools like `yarn` in it. So CI is failing - see #65 
https://drone.owncloud.com/owncloud/owncloud-test-middleware/166/3/5
```
yarn is not available on your system, please install yarn (npm install -g yarn)
```
This PR uses `owncloudci/core:nodejs14"` which has the JS tools installed.
This is a workaround for this repo for now. `owncloudci/core:latest` should really have the tools available to install any recent core for anywhere - that is its advertised functionality. I will raise …

Install core using nodejs14 docker version

---

.drone.star

This reverts commit aea7b0a383226568e289b92cbc28ab4efdc414ae.
The real problem with `owncloudci/core` docker image should have been fixed by https://github.com/owncloud-ci/core/pull/30

Revert "Install core using nodejs14 docker version"

---

src/config.js

Add assert package in config so that we can call assert using `client.assert`

add assert in config

---

src/gherkin/stepDef.test.js
src/gherkin/testContext.test.js

This pr removes `try-catch` from test scripts and uses the feature of `expect` to assert thrown errors.
Using `try-catch` for the negative conditions and again throwing errors from the body of try block makes the code look more complex and not cool. Rather we could just use the `.toThrowError` method from `expect` and assert the error messages.

Remove try catch from test scripts

---

src/stepDefinitions/publicLinkContext.js

This PR refactors a test step so that it can be used in web tests.
This change is necessary because while matching the step from `web` to middleware that uses a data table we match it by using keywords like `following` and `these`. 
The test scenario using that test step fails in the changed step in this PR and the changes made will make it pass https://github.com/owncloud/web/pull/6210

[test-only] Refactor a test step in publicLinkContext

---

src/stepDefinitions/filesContext.js

This PR adds a minor fix to the regex pattern added by PR https://github.com/owncloud/owncloud-test-middleware/pull/73
This change is necessary because tests are failing in this PR https://github.com/owncloud/web/pull/6172
Upon doing this change and the tests are passing locally

[tests-only] Minor fix to regex pattern added by PR#73

---

readme.md

These days we usually put "in the server" at the end of steps. Adjust README to do it that way in the example.
Also add more explanation about the testing app being only available on ownCloud 10, and what happens when testing against an oCIS server.

Adjust descriptions in README

---

.drone.star
Dockerfile

We are getting `Error: TypeError: folderName.replaceAll is not a function`
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replaceAll 
Support for `replaceAll` is only from Node.js 15
That code was added in PR #73 - I guess that @SwikritiT has node 15 or 16 locally and did not notice the problem.
IMO we should be able to use the later node 16 here in the middleware - it is an independent thing, not built into either the test runners or the server-under-test.

Use node 16 to support replaceAll

---

src/helpers/webdavHelper.js

This PR fixes the `getTrashBinElements` function which was stopping the middleware service in this build: https://drone.owncloud.com/owncloud/web/21732/56/16

[tests-only]Fix getTrashBinElements function

---

src/helpers/sharingHelper.js

This PR makes changes to the acceptShare , declineShare function.
These CHanges were necessary because the steps using this function were failing on OCIS in this build: https://drone.owncloud.com/owncloud/web/21808/58/16 
These changes make the tests pass locally

[tests-only]Refactor acceptShare and declineShare function to work on Ocis

---

src/helpers/webdavHelper.js

retries download after `500ms` if the first request sends `423` locked response
Similar to https://github.com/owncloud/web/pull/6303

Retry download if resource is locked

---

src/stepDefinitions/filesContext.js
src/stepDefinitions/generalContext.js

Currently, a scenario in web tests is in need of a folder with some files within for upload tests. This PR 
- adds a `Given` step to create a folder with files provided in the table
- moved `files` related steps to the `filesContext`

Added given step to create folder with files

---

Dockerfile
dev/entrypoint.sh

- populate the shared volume before starting the middleware (docker)
- why don't just use the folder in which files are already present as a shared volume? that's because docker will not sync the already present content of the shared volume dir with the other containers using that same volume. Just an empty folder is created at first. So we've to copy it after the build of the middleware container.
The docker-compose file living `owncloud/web` uses middleware and selenium as services to run web tests on different environments. For the tests involving upload steps, we need to have the files for upload inside the selenium container because the WebUI is running using the browser from the same selenium container. Now, there are two ways to make files available inside the selenium container so …

Used entrypoint to start the middleware (docker)

---

src/stepDefinitions/provisioningContext.js

Web tests in ocis recently started failing like this:
```console
Given the setting "shareapi_auto_accept_share" of app "core" has been set to "no" in the server
And the administrator has set the default folder for received shares to "Shares" in the server
And these users have been created with default attributes and without skeleton files in the server:
│ username │
│ Alice    │
│ Brian    │
│ Carol    │
Given these groups have been created in the server:
│ groupname │
│ <group>   │
✖ failed
Error: TypeError [ERR_UNESCAPED_CHARACTERS]: Request path contains unescaped characters
at new NodeError (node:internal/errors:371:5)
at new ClientRequest (node:_http_client:154:13)
at request (node:https:353:10)
at /usr/src/app/node_modules/node-fetch/lib/index.js:1438:15
at new Promise (<anonymous>) …
```

encode uri for the provisioning urls

---

readme.md
src/config.js
src/helpers/graphHelper.js
src/helpers/httpHelper.js
src/stepDefinitions/provisioningContext.js

`Given user "Alice" has been created with default attributes and without skeleton files in the server`
and
`Given these users have been created with default attributes and without skeleton files in the server:`
to graphApi
- start ocis with idm by default - branch https://github.com/owncloud/ocis/pull/3331
- start middleware with IDM variable: `BACKEND_HOST=https://localhost:9200 NODE_TLS_REJECT_UNAUTHORIZED=0 RUN_ON_OCIS=true TEST_WITH_GRAPH_API yarn start`
- init middleware: `curl -XPOST http://localhost:3000/init`
- try to create user "Alice": `curl -XPOST http://localhost:3000/execute -d '{"step": "Given user \"Alice\" has been created with default attributes and without skeleton files"}' -H "Content-Type: application/json"`
Result: Alice should be created: `curl  -k -u admin:admin …

Creating a user via graph Api

---

CHANGELOG.md
package.json

- bump version to v1.5.0
- add changelog for v1.5.0
- Part of https://github.com/owncloud/owncloud-test-middleware/issues/111

Added changelog for v1.5.0 and bumped version

---

CHANGELOG.md
package.json

- bump version to v1.6.0
- add changelog for v1.6.0
- Part of https://github.com/owncloud/owncloud-test-middleware/issues/114

Added changelog for v1.6.0 and bumped version

---

src/helpers/graphHelper.js
src/helpers/sharingHelper.js

This PR refactor code so that only successfully created user added on createdUsers array.
Refactor error message 
[Users/groups aren't being cleaned up properly after tests run in OCIS](https://github.com/owncloud/owncloud-test-middleware/issues/120)

Fix user cleanup after tests finish 

---

src/helpers/occHelper.js
src/stepDefinitions/generalContext.js
src/stepDefinitions/sharingContext.js

This PR refactor occ a related step for ocis to return. occ command in oC10 is used to set system-wide settings in oC10. Many of those things may be implemented in oCIS, but the way that the system-wide setting is done by the system administrator in oCIS will be different. Steps running occ command should be refactored for ocis.
Related issue: https://github.com/owncloud/owncloud-test-middleware/issues/123

[tests-only]Refactor occ related step for ocis

---

src/helpers/sharingHelper.js

> The expiry date should just be a date 2023-01-07. Expiry time is not supported. When the test code for the Given step calculates +10 days, it needs to just get the date, and not append any time.
https://github.com/owncloud/web/pull/8159#issuecomment-1366573099

Strip time from expiration date

---

src/helpers/webdavHelper.js

The oCIS backend may return a 425 status code when a file is still in postprocessing state. Retry behaviour should then be the same as for 423 locked.

feat: retry webdav download on 425 status code

---

src/helpers/webdavHelper.js

Single retry on 425 status codes was introduced in a9899ed1c8ccf3ee1e0867d1e33d53c0def004b9. That's not sufficient so now we change to max. 10 retries. :trollface:

feat: multiple retries webdav download on 425 status code

---

src/stepDefinitions/provisioningContext.js

this PR https://github.com/owncloud/ocis/pull/7705 changed response code when we create groups/user so update the status code expectation here too.
Hopefully a fix for https://github.com/owncloud/web/issues/9945 after middleware is bumped

Update the status code expectation for create group

---

CHANGELOG.md
src/stepDefinitions/webdavContext.js

The old implementation failed when there was a second d:propstat object in the d:response (which happens when a not found prop is added)
Should fix failure in https://github.com/owncloud/ocis/pull/7898

fix: Make webdavContext.getResourceType more resilient

---

src/helpers/sharingHelper.js

Creating a share with `share` permissions is now not supported. So i changed it for https://github.com/owncloud/ocis/pull/8704

delete share permission
