owncloud/owncloud-test-middleware

readme.md
src/app.js
src/config.js

Fixes #1 
Make Host/Port configurable
Add documentation about available config vars

Update readme with config variables and make host/port configurable

---

src/stepDefinitions/provisioningContext.js

Fix step for creating non default users
Fixes #3

Fix step for creating non default users

---

readme.md
src/stepDefinitions/generalContext.js

and some camel-case fixes in function and var names.

Minor edits to readme

---

readme.md

slashes are missing in the examples

fix URL in docs

---

src/app.js

Fixes https://github.com/owncloud/owncloud-test-middleware/issues/11

Fix the error log when the step definition is not found

---

src/app.js
src/gherkin/index.js

Fixes https://github.com/owncloud/owncloud-test-middleware/issues/12

Fix execution steps with data on single quotes

---

src/helpers/sharingHelper.js
src/helpers/testHelper.js
src/helpers/webdavHelper.js
src/stepDefinitions/sharingContext.js

This PR adds a function `customDelay` to customize the delay and remove the use of nightwatch `client.pause`
- Fixes https://github.com/owncloud/owncloud-test-middleware/issues/19

[tests-only] added function to custom delay

---

src/gherkin/step.test.js

This Pr adds unit tests for Step.
- https://github.com/owncloud/owncloud-test-middleware/issues/15

[Tests-Only]And tests for Step class

---

src/helpers/sharingHelper.js

Part of https://github.com/owncloud/owncloud-test-middleware/pull/23

[tests-only] update share permission

---

src/helpers/sharingHelper.js
src/stepDefinitions/generalContext.js
src/stepDefinitions/sharingContext.js

This PR refactors `{code}` fro step definition to `{string}`  and also adds `receiver` for change permission step done in #23.

[tests-only]refactor code to string

---

src/context/index.js
src/gherkin/index.js
src/gherkin/testContext.test.js

This PR adds unit tests for testContext.
- https://github.com/owncloud/owncloud-test-middleware/issues/15

[Tests-Only]Add tests for testContext

---

src/helpers/httpHelper.js
src/helpers/sharingHelper.js
src/stepDefinitions/publicLinkContext.js

This PR adds step to check for sharing file using public link with and without password.
https://github.com/owncloud/client/issues/8501

[tests-only] added step to for public link share

---

.drone.yml

This PR enables drone CI to run unit tests in CI.

[Tests-Only]enable drone

---

src/config.js
src/helpers/config.js
src/setup.js
src/stepDefinitions/provisioningContext.js

Update the user creation steps from https://github.com/owncloud/web/pull/4810
requires https://github.com/owncloud/owncloud-test-middleware/pull/30 to get merged first

Update user creation steps

---

src/stepDefinitions/filesContext.js

avoid race conditions by creating file and folders async
analog to https://github.com/owncloud/web/pull/4981

[tests-only] create testfiles/folders async

---

src/helpers/sharingHelper.js
src/stepDefinitions/publicLinkContext.js

This PR adds step to check if public being unable to download folder.
https://github.com/owncloud/client/pull/8561

[tests-only]added step for public unable to download folder

---

readme.md
src/app.js
src/helpers/userSettings.js

- added `/state` endpoint
- example response:
<pre><font color="#5FD700">❯</font> curl http://localhost:3000/state -v | jq  <font color="#5F8787">  19:58:37</font>
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 127.0.0.1:3000...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 3000 (#0)
&gt; GET /state HTTP/1.1
&gt; Host: localhost:3000
&gt; User-Agent: curl/7.68.0
&gt; Accept: */*
&gt; 
* Mark bundle as not supporting multiuse
&lt; HTTP/1.1 200 OK
&lt; X-Powered-By: Express
&lt; Content-Type: application/json; charset=utf-8
&lt; Content-Length: 266
&lt; ETag: W/&quot;10a-ux9MnlzEZC7TP0u8CKeRbcJioL8&quot;
&lt; Date: …

Add state endpoint

---

package.json
src/app.js
src/index.js
src/log.js
tests/testingApp/testingAppRequired.test.js
yarn.lock

Fixes https://github.com/owncloud/owncloud-test-middleware/issues/43
Add logging for easy debugging

Add logging for middleware server

---

readme.md

add link to testing app README.md for installation instructions

Add link to testing app

---

src/helpers/config.js

Set skeletonDirectory to empty folder when user is created with "without skeleton files" step

---

readme.md
src/app.js
src/config.js

Fixes https://github.com/owncloud/owncloud-test-middleware/issues/54
- fix the outdated curl commands from readme
- Ignore self signed certificates when running with ocis

Update outdated commands from readme and minor bugfix

---

.drone.star

Related https://github.com/owncloud/web/pull/5136
Add docker build step in CI

Add docker build step in CI

---

src/helpers/webdavHelper.js

This PR refactors the `createFile` function similar to that of https://github.com/owncloud/web/pull/6083
Fixes: https://github.com/owncloud/owncloud-test-middleware/issues/59

[tests-only]Store upload time after the upload is completed

---

src/stepDefinitions/webdavContext.js

Fixes https://github.com/owncloud/owncloud-test-middleware/issues/61
Fix the status code check in fileShouldNotExist function

[tests-only] fix fileNotExists function in acceptance tests

---

src/stepDefinitions/filesContext.js

Fixes: https://github.com/owncloud/owncloud-test-middleware/issues/69
This fixes the issue, for now, though it's not a really good solution. We need to come up with a better solution for this issue in future

[tests-only] Refactor regex for file/folder creation test step

---

src/stepDefinitions/sharingContext.js
src/stepDefinitions/webdavContext.js

This PR adds minor changes to the tests steps

[tests-only]Remove unnecessary steps from the middleware, minor fix to expiration 

---

src/helpers/httpHelper.js
src/helpers/webdavHelper.js

This PR adds a function related to locking files that weren't previously present.
These changes are necessary for this PR https://github.com/owncloud/web/pull/6236

[tests-only]Add functions related to locking file

---

.drone.star

Moved images to constants for easier maintain-ability, removed unnecessary "pull always" configuration and formatted the CI config

Improve starlark

---

CHANGELOG.md
package.json

- adds changelog for v1.1.0
- #79

Add changelog for v1.1.0

---

CHANGELOG.md
package.json

Description
- adds changelog for v1.1.0
fixes: https://github.com/owncloud/owncloud-test-middleware/issues/88

Add changelog for v1.2.0

---

CHANGELOG.md
package.json

- version bump
- add changelog for v1.3.0
https://github.com/owncloud/owncloud-test-middleware/issues/94

version bump and added changelog for v1.3.0

---

src/stepDefinitions/filesContext.js

- create files with provided sub-folders
- Part of https://github.com/owncloud/owncloud-test-middleware/issues/97

Fix local file create step

---

src/stepDefinitions/filesContext.js

added a step to check no. of items inside the provided folder

added steps to check items count inside a folder

---

src/stepDefinitions/filesContext.js

This was in a comment in PR #100 - may as well fix it while I notice it.

Fix typo of 'actual'

---

src/app.js

implement express endpoints in the express way

[enhancement] Adjust express endpoints

---

CHANGELOG.md
package.json

Added changelog for new version

Added changelog for v1.8.0 and bumped version

---

.eslintrc.js
src/gherkin/index.js
src/helpers/config.js
src/helpers/graphHelper.js
src/helpers/sharingHelper.js
src/helpers/userSettings.js
src/helpers/webdavHelper.js
src/stepDefinitions/sharingContext.js
src/stepDefinitions/webdavContext.js

There are different indentations used throughout the code base. With this PR:
- EsLint config is updated to set the indentation rule
- Fix indentations
Part of https://github.com/owncloud/owncloud-test-middleware/issues/78

[lint] set indentation rule

---

src/helpers/graphHelper.js

this PR https://github.com/owncloud/ocis/pull/7705 changed response code when we create users

fix response code

---

.drone.star

trying to solve CI issue `Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?`
https://drone.owncloud.com/owncloud/owncloud-test-middleware/365/5/2

update docker plugin

---

CHANGELOG.md
package.json

Update version for patch release `1.8.7` and update changelog

chore: Prepare release 1.8.7
